name: Build Windows Package

on: workflow_dispatch

jobs:

  build-win:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build Windows installer with Maven
        run: mvn -B install --file pom.xml
      - run: mkdir staging && cp target/installer/*.msi staging
      - uses: actions/upload-artifact@v2
        with:
          name: Win-MSI
          path: staging
