name: Build macOS Package

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build macOS installer with Maven
      run: mvn -B install --file pom.xml
    - run: mkdir staging && cp target/installer/*.pkg staging
    - uses: actions/upload-artifact@v3
      with:
        name: macOS-PKG
        path: staging
